# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dt = pd.read_csv ('Data.csv')
x = dt.iloc[:,: -1].values
y = dt.iloc[:,-1].values

## Taking care of missing data

In [3]:
from sklearn.impute import SimpleImputer
#Menghitung jumlah data yang kosong dan menampilkannya
  # nun = pd.isnull().sum()
# Kita membuat objek SimpleImputer yang akan mencari nilai yang hilang (np.nan) dan menggantinya dengan nilai rata-rata dari kolom yang bersangkutan.
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
# Kita melatih imputer dengan data dari kolom ke-2 dan ke-3 (x[:, 1:3]). Ini berarti imputer menghitung rata-rata untuk setiap kolom tersebut.
imputer.fit(x[:,1:3])
# Kita menggantikan nilai yang hilang pada kolom ke-2 dan ke-3 dengan rata-rata yang sudah dihitung.# Data dari kolom tersebut diimputasi (diisi) oleh imputer dan hasilnya ditugaskan kembali ke kolom yang sama di x.
x[:, 1:3] = imputer.transform(x[:,1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

Merubah isi **kolom negara dengan 0 dan 1**. **Dari pada harus jadi urutan numerik 0 higga 2**. Itu akan **membuat model ML mengira ada urutan numerik antara negara.**

In [ ]:
# Melakukan perubahan pada data kategorikal, menjadi numerik.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 1. encoder = nama bebas yang akan merujuk pada transformasi nanti,
# 2. OneHotEncoder = jenis transformasi nya yaitu merubah data katagorikal menjadi numerik
# 3. remainder 'passthrough' = Mengingatkan agar kolom yang tidak di pilih (Dibiarkan saja dan dilewatkan )
# 4. [0] = Memilih kolom pertama yg akan di lakukan

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print (y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split (x , y, test_size = 0.2, random_state = 1)

PENSKALAAN FITUR TIDAK HARUS DIlAKUKAN UNTUK SEMUA MODEL MESIN LEARNING, HANYA SEBAGIAN SAJA YANG PERLU DILAKUKAN

PENSKALAAN FITUR SENDIRI BERGUNA UNTUK AGAR MODEL TIDAK MENGANGGAP FITUR YANG LAIN LEBIH BESAR SEHINGGA MENJADIKAN MODEL (OVERFITTING)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
ct = StandardScaler()
x_train [:, 3:] = ct.fit_transform(x_train [ : , 3:])